// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"
)

type Character struct {
	ID           int32          `json:"id"`
	CaracSimpl   string         `json:"carac_simpl"`
	CaracTrad    string         `json:"carac_trad"`
	Pinyin       string         `json:"pinyin"`
	Meaning      string         `json:"meaning"`
	Category     sql.NullString `json:"category"`
	CaracAntonym sql.NullString `json:"carac_antonym"`
	CaracSimilar sql.NullString `json:"carac_similar"`
	RadicalList  sql.NullString `json:"radical_list"`
}

type HanziList struct {
	ID    int32  `json:"id"`
	Title string `json:"title"`
	// Cover image of the word list
	Svg string `json:"svg"`
}

type Radical struct {
	ID            int32  `json:"id"`
	StrokesNumber int32  `json:"strokes_number"`
	Radical       string `json:"radical"`
	Pinyin        string `json:"pinyin"`
	Meaning       string `json:"meaning"`
}

type Review struct {
	ID                 int32         `json:"id"`
	UserID             int32         `json:"user_id"`
	LastReview         time.Time     `json:"last_review"`
	CaracID            int32         `json:"carac_id"`
	Interval           sql.NullInt32 `json:"interval"`
	CreatedOn          time.Time     `json:"created_on"`
	NextReview         time.Time     `json:"nextReview"`
	TimesReviewed      int32         `json:"times_reviewed"`
	MasteryLevel       int32         `json:"mastery_level"`
	ConsecutiveCorrect int32         `json:"consecutive_correct"`
	EasinessCorrect    int32         `json:"easiness_correct"`
}

type Session struct {
	ID          sql.NullInt32 `json:"id"`
	UserID      sql.NullInt32 `json:"user_id"`
	CreatedOn   sql.NullTime  `json:"created_on"`
	CompletedOn time.Time     `json:"completed_on"`
	Duration    sql.NullInt32 `json:"duration"`
	Completed   sql.NullBool  `json:"completed"`
}

type User struct {
	ID       int       `json:"id"`
	Username string    `json:"username"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	JoinDate time.Time `json:"join_date"`
}

type Word struct {
	ID             int32          `json:"id"`
	CaracSimplList string         `json:"carac_simpl_list"`
	CaracTradList  string         `json:"carac_trad_list"`
	Pinyin         string         `json:"pinyin"`
	Meaning        string         `json:"meaning"`
	Category       sql.NullString `json:"category"`
	WordAntonym    sql.NullString `json:"word_antonym"`
	WordSimilar    sql.NullString `json:"word_similar"`
	SentencesList  sql.NullString `json:"sentences_list"`
}

type WordList struct {
	ID    int32  `json:"id"`
	Title string `json:"title"`
	// Cover image of the word list
	Svg string `json:"svg"`
}
