// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Character struct {
	ID           int32       `json:"id"`
	CaracSimpl   string      `json:"carac_simpl"`
	CaracTrad    string      `json:"carac_trad"`
	Pinyin       string      `json:"pinyin"`
	Meaning      string      `json:"meaning"`
	Category     pgtype.Text `json:"category"`
	CaracAntonym pgtype.Text `json:"carac_antonym"`
	CaracSimilar pgtype.Text `json:"carac_similar"`
	RadicalList  pgtype.Text `json:"radical_list"`
}

type HanziList struct {
	ID    int32  `json:"id"`
	Title string `json:"title"`
	// Cover image of the word list
	Svg string `json:"svg"`
}

type Radical struct {
	ID            int32  `json:"id"`
	StrokesNumber int32  `json:"strokes_number"`
	Radical       string `json:"radical"`
	Pinyin        string `json:"pinyin"`
	Meaning       string `json:"meaning"`
}

type Review struct {
	ID                 int32              `json:"id"`
	UserID             int32              `json:"user_id"`
	LastReview         pgtype.Timestamp   `json:"last_review"`
	CaracID            int32              `json:"carac_id"`
	Interval           pgtype.Int4        `json:"interval"`
	CreatedOn          pgtype.Timestamptz `json:"created_on"`
	NextReview         pgtype.Timestamp   `json:"nextReview"`
	TimesReviewed      int32              `json:"times_reviewed"`
	MasteryLevel       int32              `json:"mastery_level"`
	ConsecutiveCorrect int32              `json:"consecutive_correct"`
	EasinessCorrect    interface{}        `json:"easiness_correct"`
}

type Session struct {
	ID          pgtype.Int4        `json:"id"`
	UserID      pgtype.Int4        `json:"user_id"`
	CreatedOn   pgtype.Timestamptz `json:"created_on"`
	CompletedOn pgtype.Timestamp   `json:"completed_on"`
	Duration    pgtype.Int4        `json:"duration"`
	Completed   pgtype.Bool        `json:"completed"`
}

type User struct {
	ID       int32              `json:"id"`
	Username string             `json:"username"`
	Email    string             `json:"email"`
	Password string             `json:"password"`
	JoinDate pgtype.Timestamptz `json:"join_date"`
}

type Word struct {
	ID             int32       `json:"id"`
	CaracSimplList string      `json:"carac_simpl_list"`
	CaracTradList  string      `json:"carac_trad_list"`
	Pinyin         string      `json:"pinyin"`
	Meaning        string      `json:"meaning"`
	Category       pgtype.Text `json:"category"`
	WordAntonym    pgtype.Text `json:"word_antonym"`
	WordSimilar    pgtype.Text `json:"word_similar"`
	SentencesList  pgtype.Text `json:"sentences_list"`
}

type WordList struct {
	ID    int32  `json:"id"`
	Title string `json:"title"`
	// Cover image of the word list
	Svg string `json:"svg"`
}
