// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package sqlc

import (
	"context"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (
  username, email, password
) VALUES (
  $1::text, $2::text, $3::text
)
RETURNING id, username, email, password, join_date
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser, arg.Username, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.JoinDate,
	)
	return i, err
}

const DeleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1::int
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteUser, id)
	return err
}

const GetUserbyID = `-- name: GetUserbyID :one
SELECT id, username, email, password, join_date FROM users
WHERE id = $1::int LIMIT 1
`

func (q *Queries) GetUserbyID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, GetUserbyID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.JoinDate,
	)
	return i, err
}

const GetUserbyUsername = `-- name: GetUserbyUsername :one
SELECT id, username, email, password, join_date FROM users
WHERE username = $1::text LIMIT 1
`

func (q *Queries) GetUserbyUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, GetUserbyUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.JoinDate,
	)
	return i, err
}

const ListUsers = `-- name: ListUsers :many
SELECT id, username, email, password, join_date FROM users
ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, ListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.JoinDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
