
DROP TABLE IF EXISTS news CASCADE;
DROP TABLE IF EXISTS story_votes CASCADE;
DROP TABLE IF EXISTS stories_shared CASCADE;
DROP TABLE IF EXISTS stories CASCADE;
DROP TABLE IF EXISTS custom_keywords CASCADE;
DROP TABLE IF EXISTS learned_caractere CASCADE;
DROP TABLE IF EXISTS characters CASCADE;
DROP TABLE IF EXISTS review CASCADE;
DROP TABLE IF EXISTS user_settings CASCADE;
DROP TABLE IF EXISTS users CASCADE;