// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: character.sql

package sqlc

import (
	"context"
)

const getCharacterbyHeisigIndexSimpl = `-- name: GetCharacterbyHeisigIndexSimpl :one
SELECT ucs_id, carac_simpl, carac_trad, pinyin, meaning, type, index_heisig_simpl, index_heisig_trad FROM characters
WHERE index_heisig_simpl = $1
`

func (q *Queries) GetCharacterbyHeisigIndexSimpl(ctx context.Context, indexHeisigSimpl int32) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterbyHeisigIndexSimpl, indexHeisigSimpl)
	var i Character
	err := row.Scan(
		&i.UcsID,
		&i.CaracSimpl,
		&i.CaracTrad,
		&i.Pinyin,
		&i.Meaning,
		&i.Type,
		&i.IndexHeisigSimpl,
		&i.IndexHeisigTrad,
	)
	return i, err
}

const getCharacterbyHeisigIndexTrad = `-- name: GetCharacterbyHeisigIndexTrad :one
SELECT ucs_id, carac_simpl, carac_trad, pinyin, meaning, type, index_heisig_simpl, index_heisig_trad FROM characters
WHERE index_heisig_trad = $1
`

func (q *Queries) GetCharacterbyHeisigIndexTrad(ctx context.Context, indexHeisigTrad int32) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterbyHeisigIndexTrad, indexHeisigTrad)
	var i Character
	err := row.Scan(
		&i.UcsID,
		&i.CaracSimpl,
		&i.CaracTrad,
		&i.Pinyin,
		&i.Meaning,
		&i.Type,
		&i.IndexHeisigSimpl,
		&i.IndexHeisigTrad,
	)
	return i, err
}

const getCharacterbyID = `-- name: GetCharacterbyID :one
SELECT ucs_id, carac_simpl, carac_trad, pinyin, meaning, type, index_heisig_simpl, index_heisig_trad FROM characters
WHERE ucs_id = $1 LIMIT 1
`

func (q *Queries) GetCharacterbyID(ctx context.Context, ucsID int32) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterbyID, ucsID)
	var i Character
	err := row.Scan(
		&i.UcsID,
		&i.CaracSimpl,
		&i.CaracTrad,
		&i.Pinyin,
		&i.Meaning,
		&i.Type,
		&i.IndexHeisigSimpl,
		&i.IndexHeisigTrad,
	)
	return i, err
}
