// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Character struct {
	UcsID            int32  `json:"ucs_id"`
	CaracSimpl       string `json:"carac_simpl"`
	CaracTrad        string `json:"carac_trad"`
	Pinyin           string `json:"pinyin"`
	Meaning          string `json:"meaning"`
	Type             string `json:"type"`
	IndexHeisigSimpl int32  `json:"index_heisig_simpl"`
	IndexHeisigTrad  int32  `json:"index_heisig_trad"`
}

type CustomKeyword struct {
	ID         int32              `json:"id"`
	UserID     int32              `json:"user_id"`
	CaracUcsID int32              `json:"carac_ucs_id"`
	Keyword    string             `json:"keyword"`
	CreatedOn  pgtype.Timestamp   `json:"created_on"`
	UpdateOn   pgtype.Timestamptz `json:"update_on"`
}

type LearnedCaractere struct {
	ID         int32 `json:"id"`
	UserID     int32 `json:"user_id"`
	CaracUcsID int32 `json:"carac_ucs_id"`
}

type News struct {
	ID        int32              `json:"id"`
	Subject   string             `json:"subject"`
	CreatedOn pgtype.Timestamptz `json:"created_on"`
	UpdateOn  pgtype.Timestamp   `json:"update_on"`
	// Content of the post
	Body string `json:"body"`
}

type Review struct {
	ID           int32              `json:"id"`
	UserID       int32              `json:"user_id"`
	LastReview   pgtype.Timestamp   `json:"last_review"`
	CaracUcsID   int32              `json:"carac_ucs_id"`
	Status       string             `json:"status"`
	CreatedOn    pgtype.Timestamptz `json:"created_on"`
	ExpireDate   pgtype.Timestamp   `json:"expire_date"`
	TotalReview  int32              `json:"total_review"`
	FailureCount int32              `json:"failure_count"`
	SuccessCount int32              `json:"success_count"`
	StudyCount   int32              `json:"study_count"`
}

type StoriesShared struct {
	ID         int32              `json:"id"`
	UserID     int32              `json:"user_id"`
	CaracUcsID int32              `json:"carac_ucs_id"`
	CreatedOn  pgtype.Timestamptz `json:"created_on"`
	UpdateOn   pgtype.Timestamp   `json:"update_on"`
	Stars      int16              `json:"stars"`
	Reports    int16              `json:"reports"`
}

type Story struct {
	ID         int32              `json:"id"`
	UserID     int32              `json:"user_id"`
	CaracUcsID int32              `json:"carac_ucs_id"`
	CreatedOn  pgtype.Timestamptz `json:"created_on"`
	UpdateOn   pgtype.Timestamp   `json:"update_on"`
	// Content of the post
	Body   string `json:"body"`
	Public int32  `json:"public"`
}

type StoryVote struct {
	ID         int32              `json:"id"`
	AuthorID   int32              `json:"author_id"`
	VoterID    int32              `json:"voter_id"`
	CaracUcsID int32              `json:"carac_ucs_id"`
	CreatedOn  pgtype.Timestamptz `json:"created_on"`
	Vote       int32              `json:"vote"`
}

type User struct {
	ID       int32              `json:"id"`
	Username string             `json:"username"`
	Email    string             `json:"email"`
	Password string             `json:"password"`
	JoinDate pgtype.Timestamptz `json:"join_date"`
}

type UserSetting struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	CreatedOn pgtype.Timestamptz `json:"created_on"`
	UpdatedOn pgtype.Timestamp   `json:"updated_on"`
}
